# Generated by Django 3.2.3 on 2021-05-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=64)),
                ('continent_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=5)),
                ('capital', models.CharField(max_length=255)),
                ('calling_code', models.IntegerField()),
                ('is_eu', models.BooleanField()),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Continents', to='location_aggregator.continents')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=64)),
                ('flag_emoji', models.ImageField(upload_to='flags')),
                ('flag_emoji_unicode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('region_code', models.CharField(max_length=5)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='location_aggregator.countries')),
            ],
        ),
        migrations.AddField(
            model_name='countries',
            name='country_flag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flags', to='location_aggregator.flags'),
        ),
        migrations.AddField(
            model_name='countries',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Languages', to='location_aggregator.languages'),
        ),
        migrations.AddField(
            model_name='countries',
            name='native_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Native', to='location_aggregator.languages'),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Regions', to='location_aggregator.regions')),
            ],
        ),
    ]
