# Generated by Django 3.2.3 on 2021-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='ip',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
