# Generated by Django 3.2.3 on 2021-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0002_cities_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='continent_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flags',
            name='flag_emoji_unicode',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
