# Generated by Django 3.2.3 on 2021-05-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0005_alter_countries_calling_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='native_id',
        ),
    ]
