# Generated by Django 3.2.3 on 2021-05-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0006_remove_countries_native_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='continent_id',
            new_name='continent',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='country_flag_id',
            new_name='country_flag',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='regions',
            old_name='country_id',
            new_name='country',
        ),
    ]
