# Generated by Django 3.2.3 on 2021-05-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0007_auto_20210529_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='zip',
            new_name='zip_value',
        ),
    ]
