# Generated by Django 3.2.3 on 2021-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0010_rename_ip_cities_ip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='zip_value',
            field=models.CharField(max_length=24),
        ),
    ]
