# Generated by Django 3.2.3 on 2021-05-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0003_auto_20210526_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='location_aggregator.regions'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='calling_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='countries',
            name='continent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continents', to='location_aggregator.continents'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_flag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='location_aggregator.flags'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='location_aggregator.languages'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='native_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native', to='location_aggregator.languages'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='location_aggregator.countries'),
        ),
    ]
