# Generated by Django 3.2.3 on 2021-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0004_auto_20210527_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='calling_code',
            field=models.CharField(max_length=10),
        ),
    ]
