# Generated by Django 3.2.3 on 2021-05-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0008_rename_zip_cities_zip_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
