# Generated by Django 3.2.3 on 2021-05-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_aggregator', '0009_auto_20210529_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='ip',
            new_name='ip_code',
        ),
    ]
